version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src  # Mount the source code
      - ./static:/app/static  # Mount the static files
      - ./db/events.yaml:/app/events.yaml  # Mount the YAML file directly
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - STATIC_PATH=/app/static
      - DB_FILE_PATH=/app/events.yaml
